# ComfyUI Desktop - User Configuration
# Copy this file to ~/.config/comfyui-desktop/config.yaml
#
# Fill in the paths below to use your existing venv & ComfyUI
# instead of downloading a backend.

python_path: "/home/raka/App/ComfyUi-arwaky/venv/bin/python"
comfyui_dir: "/home/raka/App/ComfyUi-arwaky/ComfyUI"
extra_model_paths: "/home/raka/App/ComfyUi-arwaky/extra_model_paths.yaml"
output_dir: "/home/raka/SharedData/Output"
input_dir: "/home/raka/SharedData/Input"
user_dir: "/home/raka/SharedData/User"

