// PURPOSE: Config loader infrastructure — implements ConfigPort (load + ensure).

use std::path::{Path, PathBuf};
use launcher_shared::contract_config_port::ConfigPort;
use launcher_shared::{normalize_path, AppConfig, ConfigError, InstallDir};

pub struct ConfigLoader {
    config_path: PathBuf,
}

impl ConfigLoader {
    pub fn new(config_path: PathBuf) -> Self {
        Self { config_path }
    }

    fn read_existing(&self) -> Option<AppConfig> {
        if !self.config_path.exists() {
            return None;
        }
        let content = std::fs::read_to_string(&self.config_path).ok()?;
        let config: AppConfig = serde_yaml::from_str(&content).ok()?;
        if config.python_path.is_some() && config.comfyui_dir.is_some() {
            Some(config)
        } else {
            None
        }
    }
}

impl ConfigPort for ConfigLoader {
    fn load(&self) -> Result<AppConfig, ConfigError> {
        if self.config_path.exists() {
            let content = std::fs::read_to_string(&self.config_path)
                .map_err(|_e| ConfigError::NotFound(self.config_path.to_string_lossy().to_string()))?;
            serde_yaml::from_str::<AppConfig>(&content)
                .map_err(|e| ConfigError::ParseFailed(e.to_string()))
        } else {
            Err(ConfigError::NotFound(self.config_path.to_string_lossy().to_string()))
        }
    }

    fn ensure(&self, app_config_dir: &InstallDir) -> Result<AppConfig, ConfigError> {
        // Ensure directory exists
        std::fs::create_dir_all(app_config_dir.as_path())
            .map_err(|e| ConfigError::CreateFailed(e.to_string()))?;

        // If config exists and has valid paths, keep it
        if let Some(config) = self.read_existing() {
            return Ok(config);
        }

        let user_config = &self.config_path;

        let home = std::env::var("HOME").unwrap_or_default();
        let current_dir = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));

        let scan_paths = [
            ("../venv/bin/python", "../ComfyUI"),
            ("../venv/bin/python3", "../ComfyUI"),
        ];

        let abs_paths = {
            let mut v = Vec::new();
            if !home.is_empty() {
                v.push((
                    format!("{}/App/ComfyUi-arwaky/venv/bin/python", home),
                    format!("{}/App/ComfyUi-arwaky/ComfyUI", home),
                ));
            }
            v
        };

        let mut found_py = None;
        let mut found_comfy = None;
        for (py, comfy) in &scan_paths {
            let pp = current_dir.join(py);
            let cp = current_dir.join(comfy);
            if pp.exists() && cp.exists() {
                found_py = Some(normalize_path(&pp).to_string_lossy().to_string());
                found_comfy = Some(normalize_path(&cp).to_string_lossy().to_string());
                break;
            }
        }
        if found_py.is_none() {
            for (py, comfy) in &abs_paths {
                let pp = Path::new(py);
                let cp = Path::new(comfy);
                if pp.exists() && cp.exists() {
                    found_py = Some(normalize_path(pp).to_string_lossy().to_string());
                    found_comfy = Some(normalize_path(cp).to_string_lossy().to_string());
                    break;
                }
            }
        }

        if let (Some(ref py), Some(ref comfy)) = (found_py, found_comfy) {
            let out_dir = format!("{}/SharedData/Output", home);
            let in_dir = format!("{}/SharedData/Input", home);
            let user_dir = format!("{}/SharedData/User", home);
            let comfy_path = Path::new(comfy);
            let models_path = comfy_path
                .parent()
                .map(|p| p.join("extra_model_paths.yaml"))
                .filter(|p| p.exists())
                .map(|p| format!("extra_model_paths: \"{}\"\n", p.display()))
                .unwrap_or_default();
            let content = format!(
                "# Auto-generated by ComfyUI Desktop\n\
                 python_path: \"{}\"\n\
                 comfyui_dir: \"{}\"\n\
                 {}output_dir: \"{}\"\n\
                 input_dir: \"{}\"\n\
                 user_dir: \"{}\"\n",
                py, comfy, models_path, out_dir, in_dir, user_dir
            );
            if let Err(e) = std::fs::write(user_config, content) {
                eprintln!("Warning: Failed to write user config: {:?}", e);
            }
            return self.load();
        }

        let bundle = Path::new("../config.default.yaml");
        if let Some(ref src) = bundle.exists().then_some(bundle) {
            if let Err(e) = std::fs::copy(src, user_config) {
                eprintln!("Warning: Failed to copy default config: {:?}", e);
            }
        }
        self.load()
    }
}
