use tauri::Manager;

#[derive(serde::Deserialize, Default, Clone, Debug)]
pub struct AppConfig {
    pub python_path: Option<String>,
    pub comfyui_dir: Option<String>,
    pub extra_model_paths: Option<String>,
    pub output_dir: Option<String>,
    pub input_dir: Option<String>,
    pub user_dir: Option<String>,
}

pub fn read_existing_config(config_path: &std::path::Path) -> Option<AppConfig> {
    if !config_path.exists() {
        return None;
    }
    let content = std::fs::read_to_string(config_path).ok()?;
    let config: AppConfig = serde_yaml::from_str(&content).ok()?;
    if config.python_path.is_some() && config.comfyui_dir.is_some() {
        Some(config)
    } else {
        None
    }
}

pub fn ensure_user_config(app_handle: &tauri::AppHandle) {
    let Ok(config_dir) = app_handle.path().app_config_dir() else {
        return;
    };
    if let Err(e) = std::fs::create_dir_all(&config_dir) {
        eprintln!("Warning: Failed to create app config directory: {:?}", e);
    }
    let user_config = config_dir.join("config.yaml");

    // If config exists and has valid paths, keep it
    if read_existing_config(&user_config).is_some() {
        return;
    }

    let home = std::env::var("HOME").unwrap_or_default();
    let current_dir = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));

    let scan_paths = [
        ("../venv/bin/python", "../ComfyUI"),
        ("../venv/bin/python3", "../ComfyUI"),
    ];

    let abs_paths = {
        let mut v = Vec::new();
        if !home.is_empty() {
            v.push((
                format!("{}/App/ComfyUi-arwaky/venv/bin/python", home),
                format!("{}/App/ComfyUi-arwaky/ComfyUI", home),
            ));
        }
        v
    };

    let mut found_py = None;
    let mut found_comfy = None;
    for (py, comfy) in &scan_paths {
        let pp = current_dir.join(py);
        let cp = current_dir.join(comfy);
        if pp.exists() && cp.exists() {
            found_py = Some(
                crate::downloader::normalize_path(&pp)
                    .to_string_lossy()
                    .to_string(),
            );
            found_comfy = Some(
                crate::downloader::normalize_path(&cp)
                    .to_string_lossy()
                    .to_string(),
            );
            break;
        }
    }
    if found_py.is_none() {
        for (py, comfy) in &abs_paths {
            let pp = std::path::Path::new(py);
            let cp = std::path::Path::new(comfy);
            if pp.exists() && cp.exists() {
                found_py = Some(
                    crate::downloader::normalize_path(pp)
                        .to_string_lossy()
                        .to_string(),
                );
                found_comfy = Some(
                    crate::downloader::normalize_path(cp)
                        .to_string_lossy()
                        .to_string(),
                );
                break;
            }
        }
    }

    if let (Some(ref py), Some(ref comfy)) = (found_py, found_comfy) {
        let out_dir = format!("{}/SharedData/Output", home);
        let in_dir = format!("{}/SharedData/Input", home);
        let user_dir = format!("{}/SharedData/User", home);
        let comfy_path = std::path::Path::new(comfy);
        let models_path = comfy_path
            .parent()
            .map(|p| p.join("extra_model_paths.yaml"))
            .filter(|p| p.exists())
            .map(|p| format!("extra_model_paths: \"{}\"\n", p.display()))
            .unwrap_or_default();
        let content = format!(
            "# Auto-generated by ComfyUI Desktop\n\
             python_path: \"{}\"\n\
             comfyui_dir: \"{}\"\n\
             {}output_dir: \"{}\"\n\
             input_dir: \"{}\"\n\
             user_dir: \"{}\"\n",
            py, comfy, models_path, out_dir, in_dir, user_dir
        );
        if let Err(e) = std::fs::write(&user_config, content) {
            eprintln!("Warning: Failed to write user config: {:?}", e);
        }
        return;
    }

    let bundle = std::path::Path::new("../config.default.yaml");
    let resource = app_handle
        .path()
        .resource_dir()
        .ok()
        .map(|d| d.join("config.default.yaml"));
    let src = if bundle.exists() {
        Some(bundle.to_path_buf())
    } else {
        resource.filter(|p| p.exists())
    };
    if let Some(ref src) = src {
        if let Err(e) = std::fs::copy(src, &user_config) {
            eprintln!(
                "Warning: Failed to copy default config to user config: {:?}",
                e
            );
        }
    }
}

pub fn read_app_config(app_handle: &tauri::AppHandle) -> AppConfig {
    let check_path = |path: &std::path::Path| -> Option<AppConfig> {
        if path.exists() {
            if let Ok(content) = std::fs::read_to_string(path) {
                if let Ok(config) = serde_yaml::from_str::<AppConfig>(&content) {
                    return Some(config);
                }
            }
        }
        None
    };

    if let Some(config) = check_path(std::path::Path::new("config.yaml")) {
        return config;
    }

    if let Some(config) = check_path(std::path::Path::new("../config.yaml")) {
        return config;
    }

    if let Ok(config_dir) = app_handle.path().app_config_dir() {
        let config_file = config_dir.join("config.yaml");
        if let Some(config) = check_path(&config_file) {
            return config;
        }
    }

    AppConfig::default()
}
